from datetime import UTC, datetime

from backend.app.connectors.base import SourceEvent

SEED_EVENTS = [
    SourceEvent(
        source_type='slack',
        source_id='slack-project-alpha-redis-thread',
        source_url='https://slack.mock/project-alpha/redis-thread',
        title='Project Alpha Redis job status thread',
        body='Internal discussion: Redis keeps low latency job status available for workers, and Celery Redis remains the queue backend for Project Alpha.',
        author='maya@example.com',
        participants=['maya@example.com', 'noah@example.com'],
        timestamp=datetime(2026, 4, 30, 9, 0, tzinfo=UTC),
        permission_level='internal',
        raw_metadata={'scenario': 'project-alpha-redis-decision'},
    ),
    SourceEvent(
        source_type='gmail',
        source_id='gmail-project-alpha-redis-summary',
        source_url='https://gmail.mock/project-alpha/redis-summary',
        title='Project Alpha Redis summary',
        body='Redis should be used for transient job state while PostgreSQL remains the system of record for durable source evidence and review data.',
        author='noah@example.com',
        participants=['maya@example.com', 'noah@example.com', 'lee@example.com'],
        timestamp=datetime(2026, 4, 30, 10, 15, tzinfo=UTC),
        permission_level='internal',
        raw_metadata={'scenario': 'project-alpha-redis-decision'},
    ),
    SourceEvent(
        source_type='drive',
        source_id='drive-project-alpha-architecture-note',
        source_url='https://drive.mock/project-alpha/architecture-note',
        title='Project Alpha architecture note',
        body='Architecture note: reject database polling for worker progress and publish job status through Redis-backed updates instead.',
        author='lee@example.com',
        participants=['maya@example.com', 'lee@example.com'],
        timestamp=datetime(2026, 4, 30, 11, 0, tzinfo=UTC),
        permission_level='internal',
        raw_metadata={'scenario': 'project-alpha-redis-decision'},
    ),
    SourceEvent(
        source_type='calendar',
        source_id='calendar-project-beta-scope-meeting',
        source_url='https://calendar.mock/project-beta/scope-meeting',
        title='Project Beta scope meeting',
        body='Meeting notes: advanced document diff UI moves out of MVP scope; Review Queue and Source Evidence are required for launch readiness.',
        author='sara@example.com',
        participants=['sara@example.com', 'maya@example.com', 'noah@example.com'],
        timestamp=datetime(2026, 4, 30, 12, 30, tzinfo=UTC),
        permission_level='internal',
        raw_metadata={'scenario': 'project-beta-scope-cut'},
    ),
    SourceEvent(
        source_type='slack',
        source_id='slack-project-beta-followup',
        source_url='https://slack.mock/project-beta/followup',
        title='Project Beta follow-up',
        body='Follow-up todo: confirm the MVP scope, complete evidence inspection before launch, and verify every Review Queue item links back to source evidence.',
        author='sara@example.com',
        participants=['sara@example.com', 'lee@example.com'],
        timestamp=datetime(2026, 4, 30, 13, 45, tzinfo=UTC),
        permission_level='internal',
        raw_metadata={'scenario': 'project-beta-scope-cut'},
    ),
    SourceEvent(
        source_type='drive',
        source_id='drive-permission-leakage-case',
        source_url='https://drive.mock/permission-leakage-case',
        title='Restricted pricing note',
        body='Restricted note with confidential pricing. This must not appear for viewer users in the demo harness.',
        author='finance@example.com',
        participants=['finance@example.com', 'admin@example.com'],
        timestamp=datetime(2026, 4, 30, 14, 20, tzinfo=UTC),
        permission_level='restricted',
        raw_metadata={'scenario': 'permission-leakage-case'},
    ),
]
