"""add project_key to knowledge models

Revision ID: 5f8d874023d7
Revises: 0001_create_current_schema
Create Date: 2026-05-14 10:19:00.988396
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '5f8d874023d7'
down_revision = '0001_create_current_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_records', sa.Column('project_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_decision_records_project_key'), 'decision_records', ['project_key'], unique=False)
    op.add_column('history_events', sa.Column('project_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_history_events_project_key'), 'history_events', ['project_key'], unique=False)
    op.add_column('timeline_events', sa.Column('project_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_timeline_events_project_key'), 'timeline_events', ['project_key'], unique=False)
    op.add_column('todos', sa.Column('project_key', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_todos_project_key'), 'todos', ['project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_project_key'), table_name='todos')
    op.drop_column('todos', 'project_key')
    op.drop_index(op.f('ix_timeline_events_project_key'), table_name='timeline_events')
    op.drop_column('timeline_events', 'project_key')
    op.drop_index(op.f('ix_history_events_project_key'), table_name='history_events')
    op.drop_column('history_events', 'project_key')
    op.drop_index(op.f('ix_decision_records_project_key'), table_name='decision_records')
    op.drop_column('decision_records', 'project_key')
    # ### end Alembic commands ###
