"""add project_key to knowledge models

Revision ID: 5f8d874023d7
Revises: 0001_create_current_schema
Create Date: 2026-05-14 10:19:00.988396
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect

revision = '5f8d874023d7'
down_revision = '0001_create_current_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    _add_column_if_missing('decision_records', sa.Column('project_key', sa.String(length=64), nullable=True))
    _create_index_if_missing('ix_decision_records_project_key', 'decision_records', ['project_key'])
    _add_column_if_missing('history_events', sa.Column('project_key', sa.String(length=64), nullable=True))
    _create_index_if_missing('ix_history_events_project_key', 'history_events', ['project_key'])
    _add_column_if_missing('timeline_events', sa.Column('project_key', sa.String(length=64), nullable=True))
    _create_index_if_missing('ix_timeline_events_project_key', 'timeline_events', ['project_key'])
    _add_column_if_missing('todos', sa.Column('project_key', sa.String(length=64), nullable=True))
    _create_index_if_missing('ix_todos_project_key', 'todos', ['project_key'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_project_key'), table_name='todos')
    op.drop_column('todos', 'project_key')
    op.drop_index(op.f('ix_timeline_events_project_key'), table_name='timeline_events')
    op.drop_column('timeline_events', 'project_key')
    op.drop_index(op.f('ix_history_events_project_key'), table_name='history_events')
    op.drop_column('history_events', 'project_key')
    op.drop_index(op.f('ix_decision_records_project_key'), table_name='decision_records')
    op.drop_column('decision_records', 'project_key')
    # ### end Alembic commands ###


def _add_column_if_missing(table_name: str, column: sa.Column) -> None:
    inspector = inspect(op.get_bind())
    column_names = {item['name'] for item in inspector.get_columns(table_name)}
    if column.name not in column_names:
        op.add_column(table_name, column)


def _create_index_if_missing(index_name: str, table_name: str, columns: list[str]) -> None:
    inspector = inspect(op.get_bind())
    index_names = {item['name'] for item in inspector.get_indexes(table_name)}
    if index_name not in index_names:
        op.create_index(index_name, table_name, columns, unique=False)
